### ISSUE TITLE
Übersetzung fehlerhaft

### ISSUE THREAD

**Issue by s-woe** [MicrosoftDocs/cpp-docs.de-de#23]
"Wenn LIB eine Importbibliothek erstellt wird, wird auch eine .exp-Datei. Verwenden Sie die EXP-Datei, wenn Sie ein Programm, die exportiert verknüpfen in und aus einem anderen Programm importiert wird, entweder direkt oder indirekt. Wenn Sie eine mit einer EXP-Datei Verknüpfung, ergibt LINK keine Importbibliothek, da es wird davon ausgegangen, dass LIB noch nicht erstellt. Details zu .exp-Dateien und Importbibliotheken, finden Sie unter arbeiten mit Importbibliotheken und Exportdateien"

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 462e02ff-dc58-0751-f68e-a08bdd4ce266
* Version Independent ID: d1282818-ecfa-a543-53f2-a0fa5ec15ce0
* Content: [.EXP-Dateien als Eingabe für den Linker](https://docs.microsoft.com/de-de/cpp/build/reference/dot-exp-files-as-linker-input?view=vs-2019#feedback)
* Content Source: [docs/build/reference/dot-exp-files-as-linker-input.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/build/reference/dot-exp-files-as-linker-input.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Hallo, @s-woe

Vielen Dank für Ihr Feedback. 

Ihre Kommentare werden aktuell von uns geprüft. Wir melden uns bald bei Ihnen. 

Mit freundlichen Grüßen 
das Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo, @s-woe 
Wir freuen uns über Ihren Kommentar und bemühen uns, Ihre Erfahrungen mit docs.microsoft.com zu verbessern. Wir benötigen jedoch weitere Informationen, um auf Ihr Feedback eingehen zu können. Können Sie uns bitte nähere Informationen geben und Ihren Kommentar erläutern?
Mit freundlichen Grüßen
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @s-woe
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
