### ISSUE TITLE
C++ keyword `char` translated to `Char` in German translation

### ISSUE THREAD

**Issue by smuehlst** [MicrosoftDocs/cpp-docs.de-de#25]
The German translation of the text

> The char type was the original character type in C and C++. The type unsigned char is often used

is

> Die Char Typ war der ursprüngliche Zeichentyp in C und C++. Der Typ unsigned Char dient häufig

Note that the lowercase `char` gets translated to uppercase `Char`. This is wrong as `char` is a keyword in C++ and must not be modified by translation.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 59b96635-cde4-f0e6-8848-606d346cb714
* Version Independent ID: 3745162c-993e-5f89-1188-bb3077d3a23d
* Content: [char, wchar_t, char16_t, char32_t](https://docs.microsoft.com/de-de/cpp/cpp/char-wchar-t-char16-t-char32-t?view=vs-2019#feedback)
* Content Source: [docs/cpp/char-wchar-t-char16-t-char32-t.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/cpp/char-wchar-t-char16-t-char32-t.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @smuehlst
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @smuehlst 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/cpp/cpp/char-wchar-t-char16-t-char32-t?view=vs-2019#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
