### ISSUE TITLE
Example function does not compile.

### ISSUE THREAD

**Issue by DotBlack** [MicrosoftDocs/cpp-docs.de-de#28]
Hello.
void test( char * format, ... ) needs to be 
void test( const char * format, ... ) because "%d %c %d"
is a const char array and can't implicitly convert to a char*.
Can you maybe update the test function?
Thank you! 

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: df8d5020-450c-0b03-8588-a2dcf3e0a84d
* Version Independent ID: fc463135-65e1-dba0-2f9a-b1ef329818f8
* Content: [vsprintf, _vsprintf_l, vswprintf, _vswprintf_l, __vswprintf_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l?view=vs-2019#feedback)
* Content Source: [docs/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/vsprintf-vsprintf-l-vswprintf-vswprintf-l-vswprintf-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @DotBlack
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #1541](https://github.com/MicrosoftDocs/cpp-docs/issues/1541) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @DotBlack,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/1541

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
