### ISSUE TITLE
German translation "show" -> "auftritt" wrong

### ISSUE THREAD

**Issue by UnePierre** [MicrosoftDocs/cpp-docs.de-de#31]
The pragma parameter is a name that must not be localized.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: bdeaa85c-b414-742d-156e-1b9d031c5913
* Version Independent ID: 252a08e0-cf80-6788-7d8a-f15ef7a77e17
* Content: [pack-Pragma](https://docs.microsoft.com/de-de/cpp/preprocessor/pack?view=vs-2019#feedback)
* Content Source: [docs/preprocessor/pack.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/preprocessor/pack.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @UnePierre
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @UnePierre 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/cpp/preprocessor/pack?view=vs-2019#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
