### ISSUE TITLE
It's "Destruktor" and not "debugtor"

### ISSUE THREAD

**Issue by csware** [MicrosoftDocs/cpp-docs.de-de#35]
Destructors are consequently wrongly translated as "debugtor". Should be "Destrutor".

**Comment by csware** [comment]
Example: <https://docs.microsoft.com/de-de/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4265?view=vs-2019>

**Comment by srvbpigh** [comment]
Hello, @csware
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @csware 

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/de-de/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4265?view=vs-2019

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team

**Comment by csware** [comment]
It's still "debugtor" right now.

**Comment by FastInvite2k2** [comment]
@csware 

They don't seem to care.
