### ISSUE TITLE
Automatic translation to German is buggy

### ISSUE THREAD

**Issue by holvo** [MicrosoftDocs/cpp-docs.de-de#36]
The automatic translation to German is buggy. Where is the button to switch back to English?

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: c5dddf05-db36-48f3-8534-2464bd59082e
* Version Independent ID: 4b7de78f-1c5a-3892-cafc-f6c5d0af4d6c
* Content: [strncpy, _strncpy_l, wcsncpy, _wcsncpy_l, _mbsncpy, _mbsncpy_l](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/strncpy-strncpy-l-wcsncpy-wcsncpy-l-mbsncpy-mbsncpy-l?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DDE-DE%26k%3Dk(STRING%2Fstrncpy);k(strncpy);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/strncpy-strncpy-l-wcsncpy-wcsncpy-l-mbsncpy-mbsncpy-l.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/strncpy-strncpy-l-wcsncpy-wcsncpy-l-mbsncpy-mbsncpy-l.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @holvo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @JasonCard 
can you please check this issue? The "Read in English" feature is not available in this page

**Comment by JasonCard** [comment]
Hi @holvo, @CeciAc 
Thank you for checking.
The "Read in English" toggle had issues that needed to be fixed, so it's currently disabled for all DOCS content while the feature is being improved.
Thank you for your patience and please use the Language Selection link at the bottom left of DOCS page to select your preferred language.

Kind regards,
Microsoft DOCS International Team
