### ISSUE TITLE
Incorrect translation: "form" (as in shape) > "Formular"

### ISSUE THREAD

**Issue by mootari** [MicrosoftDocs/cpp-docs.de-de#38]
In the paragraph

> Durch das zweite Syntaxformat wird ein funktionsähnliches Makro mit Parametern definiert. Dieses **Formular** akzeptiert eine optionale Liste von Parametern, die in Klammern angegeben sein müssen. Nachdem das Makro definiert wurde, wird jedes nachfolgendeVorkommen des Bezeichners (bezeichneropt,...,bezeichneropt) durch eine Version des tokenzeichenfolgenarguments ersetzt, das über tatsächliche Argumente verfügt. formale Parameter werden ersetzt.

the original "form" (as in shape, signature) was translated as "Formular". The correct translation should be "Form".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 97fd6e1e-08ca-04a7-fa81-3b9d55005d34
* Version Independent ID: 40ff5926-9706-4a15-3e4d-3d6ea965b9a7
* Content: [##define-Anweisung (C/C++)](https://docs.microsoft.com/de-de/cpp/preprocessor/hash-define-directive-c-cpp?view=vs-2019)
* Content Source: [docs/preprocessor/hash-define-directive-c-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/preprocessor/hash-define-directive-c-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by mootari** [comment]
There are several more instances of this mistranslation. A few examples:
- https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/8aac949055a828bcb5a570ecdf259b9e382a8ce0/docs/cpp/unhook.md
- https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/a94e4c3ab6c201969f3d378dab527682c039e5ce/docs/c-language/structure-and-union-members.md
- https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/3d114a4ea71f674e21aa24558d60e9514e7f6815/docs/assembler/masm/dosseg.md
- https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/7ff9cf0debdd9ba406562d811273e2e3cbb198a8/docs/c-runtime-library/reference/floating-point-ordering.md

**Comment by srvbpigh** [comment]
Hello, @mootari
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello @mootari:

Thank you for your contribution. 

Contributions on translation problems against machine translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
