### ISSUE TITLE
Bad German Translation

### ISSUE THREAD

**Issue by pks** [MicrosoftDocs/cpp-docs.de-de#41]
The German translation of this page is not very good, for example the sentence 
> Die OMP_NESTED-Umgebungsvariable aktiviert oder deaktiviert die gemutete Parallelität, es sei denn, die gemusterte Parallelität wird durch Aufrufen der omp_set_nested Bibliotheks Routine aktiviert oder deaktiviert.

is hardly recognisable since the words "gemutete" and "gemusterte" are completely out of place.

Another example is the translation of "DOS:" (the OS) to "Aussprechen" (literally translated back to "Pronounciate"), also note the missing colon.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 87f154e3-4062-6dba-5a78-38f4592ef642
* Version Independent ID: 1465fb66-72a7-23fa-2614-8291ddd7fbb4
* Content: [4. Umgebungsvariablen](https://docs.microsoft.com/de-de/cpp/parallel/openmp/4-environment-variables?view=vs-2019#44-omp_nested)
* Content Source: [docs/parallel/openmp/4-environment-variables.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/parallel/openmp/4-environment-variables.md)
* Product: **visual-cpp**
* Technology: **cpp-parallel**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @pks
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hallo @pks 

Vielen Dank für Ihren Beitrag. 

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert. 

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen. 

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung. 

Vielen Dank für Ihre Unterstützung! 

Microsoft DOCS Global Experience Team
