### ISSUE TITLE
Warning is triggered for functions that might throw

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/cpp-docs.de-de#46]
Functions that do properly acquire and release locks may still trigger this warning if they might throw. The following code triggers C26110 for `~scoped_lock` if and only if `GetMutex()` is _not_ declared `noexcept`.
```
std::mutex& GetMutex() /*noexcept*/
{
  static std::mutex m;
  return m;
}

std::scoped_lock lock(GetMutex());   // warning C26110
```
IMHO, the documentation should clarify that "... other lock-related annotations _on at least one path of execution - including exceptions_." in the first paragraph and maybe add the above as a second example.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 7b8f0de0-364e-09d2-e133-db938f09ce44
* Version Independent ID: fc7a9431-5799-032d-fc93-b468e6c606b5
* Content: [C26110](https://docs.microsoft.com/de-de/cpp/code-quality/c26110?view=vs-2019)
* Content Source: [docs/code-quality/c26110.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/code-quality/c26110.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @FrankHeimes
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @FrankHeimes, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/2251. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
