### ISSUE TITLE
übersetzte Funktions/Makronamen

### ISSUE THREAD

**Issue by TheJonny** [MicrosoftDocs/cpp-docs.de-de#47]
[Hier Feedback eingeben]

In der Seite zu realloc sind Namen von Funktionen übersetzt, und sogar verschieden

https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/realloc?view=vs-2019

es gibt da `rezuzuweisung`, Die `rezubelegungs` Funktion, `czuzuordnungsbefehl`, `rebelegc`, `null` (kleingeschrieben)

Wenn man nicht schon weiß, was die Funktion tut, ist die seite völlig unverständlich

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: b80bdfbd-3324-0b2e-7fac-35d19bac8233
* Version Independent ID: 8566607c-e99e-4c57-fede-4fe256f25cd9
* Content: [realloc](https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/realloc?view=vs-2019)
* Content Source: [docs/c-runtime-library/reference/realloc.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/c-runtime-library/reference/realloc.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by srvbpigh** [comment]
Hello, @TheJonny
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by TheJonny** [comment]
oh, and the translation "Kosten" (cost/price) for "free()" ist funny, too

**Comment by TylerMSFT** [comment]
German->English: n the page to realloc are translated names of functions, and even different
https://docs.microsoft.com/de-de/cpp/c-runtime-library/reference/realloc?view=vs-2019
there is reassignment, the reassignment function, czuassignment command, rebelegc, null (lowercase)

If you don't already know what the function is doing, the page is completely incomprehensible

**Comment by CeciAc** [comment]
Hallo @TheJonny 

Vielen Dank für Ihren Beitrag.

Beiträge zu Übersetzungsproblemen in maschinell übersetzten Inhalten werden zurzeit nicht akzeptiert.

Wir schätzen Ihr Feedback und Ihre Vorschläge zu von Menschen übersetzten Inhalten. Diese werden verwendet, um die Engines für maschinelle Übersetzung zu trainieren. Mit der Zeit verbessern Ihre Beiträge also die Qualität menschlicher und maschineller Übersetzungen.

Anhand des ms.translationtype-Metadatenwerts im Header einer Inhaltsdatei können Sie zwischen menschlicher und maschineller Übersetzung unterscheiden. Dabei steht „HT“ für menschliche Übersetzung und „MT“ für maschinelle Übersetzung.

Vielen Dank für Ihre Unterstützung!

Microsoft DOCS Global Experience Team

**Comment by JasonCard** [comment]
Hi @TheJonny 

Thank you for your feedback.
I'll follow up with writer to prevent this over-localization issue by MT.


Best regards,
Jason
