### ISSUE TITLE
_com_ptr_t is implicitly convertible to just about anything

### ISSUE THREAD

**Issue by FrankHeimes** [MicrosoftDocs/cpp-docs.de-de#48]
Those who consider using `_com_ptr_t` should be aware that this type converts to just about anything. The following code compiles fine without any warnings or errors:
```
using IStreamPtr = _com_ptr_t<_com_IIID<IStream, &__uuidof(IStream)>>;
IStreamPtr p;
const bool b = p;
const int i = p;
const long l = p;
```
This is caused by the `operator bool() const noexcept` member of `_com_ptr_t`, which is implicitly converted to `int`, `long` or any other POD type. So `b == true` and `i == l == 1` if the interface pointer is not `NULL`.

If `IStreamPtr` was an alias for `void*`, then that code would trigger
_warning C4800: Implicit conversion from 'IStreamPtr' to bool. Possible information loss
error C2440: 'initializing': cannot convert from 'IStreamPtr' to 'int'_

Granted - the `bool()` cast operator has been implemented to support statements like `if (p) {...}` and warning C4800 can be enabled by including `comip.h` with warning level 4 enabled. But this still does not catch the situation where an interface is inadvertently passed as an `int` or `long` parameter.

It is highly unlikely that Microsoft will modify `_com_ptr_t` as this could break a large existing code base.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 6cdedf5f-d1b3-3a53-352b-23dfeccf775b
* Version Independent ID: 401c4a01-5117-250d-8b5f-78410c0db84b
* Content: [Vorgehensweise: Erstellen und Verwenden von CComPtr-und CComQIPtr-Instanzen](https://docs.microsoft.com/de-de/cpp/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances?view=vs-2019)
* Content Source: [docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/cpp/how-to-create-and-use-ccomptr-and-ccomqiptr-instances.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @FrankHeimes
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2260](https://github.com/MicrosoftDocs/cpp-docs/issues/2260) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @FrankHeimes, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/2260. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
