### ISSUE TITLE
Allow warning levels as option for /We

### ISSUE THREAD

**Issue by Febbe** [MicrosoftDocs/cpp-docs.de-de#59]
[Hier Feedback eingeben]
I want to know, how to treat specific warning levels as errors, or how to specify a range of warnings as error:
e.g: `/W4 /We 1; 2; 3` # treat warning level 1-3 as errors, but show the rest as warnings
or `/W4 /We [1000:1999]` tread all warnings from W 1000 until 1999 as error, but show warnings until `/W4`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 5982a585-1e84-e997-e785-b641427ab32f
* Version Independent ID: 0a55004f-2c4f-8462-da84-2f6d0d43e50e
* Content: [/w, /W0, /W1, /W2, /W3, /W4, /w1, /w2, /w3, /w4, /Wall, /wd, /we, /wo, /Wv, /WX (Warnstufe)](https://docs.microsoft.com/de-de/cpp/build/reference/compiler-option-warning-level?view=msvc-160)
* Content Source: [docs/build/reference/compiler-option-warning-level.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/build/reference/compiler-option-warning-level.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@Febbe 
Those sound like interesting and useful features. Unfortunately, the product doesn't support them. To make a product suggestion, you can use the **Help > Send Feedback > Suggest a Feature** ("Vorschlag senden", vielleicht) command in Visual Studio, or use [Suggest a feature](https://aka.ms/feedback/suggest?space=62) on the Visual Studio Developer Community forum. Best of luck!
