### ISSUE TITLE
Clusters instead of list and map

### ISSUE THREAD

**Issue by svenbieg** [MicrosoftDocs/cpp-docs.de-de#6]
I have written an algorithm which can order and sort large numbers of items in real-time.
It creates a directory-tree in form of a pyramid, moving items and groups accordingly.

You can find further Information on my website at http://svenbieg.azurewebsites.net/clusters.

I hope my solution will make it into the standard-library!

Best regards,

Sven Bieg

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: dc3f34a7-062a-f199-f31e-d35e0444d9be
* Version Independent ID: 5fba6de8-b958-f9e7-b0b6-059ec6ac8cf6
* Content: [Headerdateien der C++-Standardbibliothek](https://docs.microsoft.com/de-de/cpp/standard-library/cpp-standard-library-header-files?view=vs-2017)
* Content Source: [docs/standard-library/cpp-standard-library-header-files.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/standard-library/cpp-standard-library-header-files.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by LisandroSu** [comment]
Hello, @svenbieg ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
