### ISSUE TITLE
Text "warning" is translated to German in code parts ("pragma Warnnung"). Mark text as don't translate.

### ISSUE THREAD

**Issue by jmeidert** [MicrosoftDocs/cpp-docs.de-de#60]
[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9651a718-4fc5-35ea-f5d8-b3d4fc355639
* Version Independent ID: be36f8da-7c38-53c7-7d25-c9ea1f0f6755
* Content: [warning-Pragma](https://docs.microsoft.com/de-de/cpp/preprocessor/warning?view=msvc-160#feedback)
* Content Source: [docs/preprocessor/warning.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/preprocessor/warning.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@jmeidert 
I've restyled the source documents for proper internationalization. It may take some time to work through the localization process, perhaps two or three weeks.
