### ISSUE TITLE
Englischer Text ist teils auf Deutsch

### ISSUE THREAD

**Issue by weidenbach** [MicrosoftDocs/cpp-docs.de-de#62]
Ich lese den Text auf Englisch, weil das Original besser verständlich ist als eine automatische Übersetzung ("Auf Englisch lesen" ist aktiviert). Nun ist ein Abschnitt vom Text allerdings auf Deutsch. Die ersten beiden Sätze sind ja noch verständlich, aber dann wird es komisch:

Beachten Sie, dass die Werte in beide Richtungen neu interpretiert werden. Wenn Ihr Programm seltsame Ergebnisse erzeugt, in denen das Vorzeichen des Werts anders als erwartet umgekehrt erscheint, suchen Sie nach impliziten Konvertierungen zwischen ganzzahligen Typen mit und ohne Vorzeichen. **Im folgenden Beispiel wird das Ergebnis des Ausdrucks (0-1) implizit von in konvertiert, int unsigned int Wenn es in gespeichert wird num . This causes the bit pattern to be reinterpreted.**

Der Rest vom Artikel ist auf Englisch.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4febd6ec-05d8-97cf-fb9f-fc41e4ee2142
* Version Independent ID: afe287bd-011f-90f2-eef4-2559e405d277
* Content: [Typumwandlungen und Typsicherheit](https://docs.microsoft.com/de-de/cpp/cpp/type-conversions-and-type-safety-modern-cpp?view=msvc-160)
* Content Source: [docs/cpp/type-conversions-and-type-safety-modern-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/cpp/type-conversions-and-type-safety-modern-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JasonCard This is a curious issue where part of one paragraph in the document remains in German when "Read in English" ("Auf Englisch lesen") is selected. I don't see anything unexpected in the English source for the offending paragraph, at line 71. Is this a known issue?

**Comment by weidenbach** [comment]
If it helps, here is an image of how I see the page (added two red lines to highlight the discussed paragraph). Weirdly. the last sentence of the paragraph is English again.
![grafik](https://user-images.githubusercontent.com/73471359/114708186-59c26a00-9d2b-11eb-8175-47e2f2c7d9b6.png)

**Comment by corob-msft** [comment]
@weidenbach 
Yes, that's what I saw. Sorry it's behaving strangely. Someone on the Docs internationalization team will look at this issue.

**Comment by JasonCard** [comment]
@weidenbach @corob-msft Thank you for reporting this issue and bringing it to my attention. It repros in all languages and I've opened an incident ticket for further investigation.

**Comment by JasonCard** [comment]
@weidenbach @corob-msft Thank you again and this issue is now fixed.
