### ISSUE TITLE
1 configurations have been excluded, because they are present in output directories

### ISSUE THREAD

**Issue by maximiliankamps** [MicrosoftDocs/cpp-docs.de-de#64]
Hi,

When I open in VisualStudio 2019 with File-Open-Cmake a file "CMakeLists.txt" I get the following warning:
"Warnung: 1 Konfigurationen wurden ausgeschlossen, da sie in Ausgabeverzeichnissen vorhanden sind."
(In English something like "1 configurations have been excluded, because they are present in output directories".
Furthermore Visual Studio does not generate a configuration and does not create an out/build directory and does not start cmake.

I could not find any information on the above warning (which is in fact an error) in the Internet.

Do you have any idea what goes wrong?

Here is the CmakeLists,txt file I tried to open:

cmake_minimum_required(VERSION 3.10 FATAL_ERROR)
project(ECG VERSION 1.0 LANGUAGES C CXX DESCRIPTION "Echtzeit Computer Grafik")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release)
endif()

if(CMAKE_COMPILER_IS_GNUCXX)
    message(STATUS "GCC detected, adding compile flags")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra")
    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -g -Og")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -O3 -march=native")
endif(CMAKE_COMPILER_IS_GNUCXX)
if(WIN32)
    add_definitions(-DNOMINMAX)
    set(GLSLC glslc.exe) 
else()
    set(GLSLC glslc)
endif(WIN32)

add_subdirectory(TGA)
add_subdirectory(Framework)
add_subdirectory(heightmap_viewer)
add_subdirectory(Assignments)

[Hier Feedback eingeben]

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 4417dbbb-58ad-4417-3a96-c1cb40516ca2
* Version Independent ID: cb5427c7-ee24-c972-bc44-ff890621cbf9
* Content: [CMakeSettings.json-Schemareferenz](https://docs.microsoft.com/de-de/cpp/build/cmakesettings-reference?view=msvc-160)
* Content Source: [docs/build/cmakesettings-reference.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/build/cmakesettings-reference.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@maximiliankamps 
I'm sorry you're having trouble. I recommend a support channel, such as [Microsoft Docs Q&A](https://docs.microsoft.com/answers/topics/c%2B%2B.html) or [Developer Community](https://aka.ms/vsfeedback/browsecpp), for questions like yours I'm closing this issue because there isn't an obvious issue in the documentation for us to fix.
