### ISSUE TITLE
Where's the UI Styleguide

### ISSUE THREAD

**Issue by OneWorld123** [MicrosoftDocs/cpp-docs.de-de#7]
I know there is one for good old MFC. Where is it??

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 42049e75-368d-47a1-5e02-120f63ca206e
* Version Independent ID: 8e59fa96-5439-9a3e-8fe2-9b0c0e4dcee9
* Content: [MFC-Konzepte](https://docs.microsoft.com/de-de/cpp/mfc/mfc-concepts?view=vs-2017)
* Content Source: [docs/mfc/mfc-concepts.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/mfc/mfc-concepts.md)
* Product: **visual-cpp**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by LisandroSu** [comment]
Hello, @OneWorld123 
 
We are following up on our previous comment. We need more information in order be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @OneWorld123 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team

**Comment by OneWorld123** [comment]
Hi, sorry I had no time yet to reply. I mean a document that is very
specific on how labels and textboxes in a MFC style dialog must be
arranged. E.g. there are margins in pixel specified. I have seen that
webpage two month ago on your webpage. But unfortunately I am no longer
able to find that page again.

Am Mi., 10. Okt. 2018 um 21:41 Uhr schrieb Lisandro <
notifications@github.com>:
