### ISSUE TITLE
Translation is useless

### ISSUE THREAD

**Issue by CanastraRF** [MicrosoftDocs/cpp-docs.de-de#8]
the automatic Translation of  _DATE_ _TIME_ _FILE_ and _LINE_ to german _Datum_ _Zeit_ _Datei_ and _Zeile_ is useless

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 302c807b-34ed-c367-be11-c1528666cb75
* Version Independent ID: acf8ddce-337a-1a41-d39e-b7d2b52360cf
* Content: [Vordefinierte Makros](https://docs.microsoft.com/de-de/cpp/preprocessor/predefined-macros?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DDE-DE%26k%3Dk(__cplusplus);k(DevLang-C%2B%2B);k(TargetOS-Windows)%26rd%3Dtrue&view=vs-2017)
* Content Source: [docs/preprocessor/predefined-macros.md](https://github.com/MicrosoftDocs/cpp-docs.de-de/blob/live/docs/preprocessor/predefined-macros.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Hello, @CanastraRF

Thank you for your feedback. The page in question has been machine-translated, which is not always perfectly understandable. We recently added a "Read in English/Auf Englisch lese" option on the right which allows you to switch to the English version without having to change the language settings.

Kind regards,
Microsoft DOCS International Team
